### ISSUE TITLE
Somehow hosed my pier with pongo

### ISSUE THREAD

**Issue by kingdonb** [uqbar-dao/pongo#23]
I'm not really sure what has happened but:

```
http: web interface live on https://localhost:443
http: web interface live on http://localhost:80
http: loopback live on http://localhost:12321
pier (126406512): live
kiln: merge into %pongo succeeded
gall: reloading %pongo
behn: bail 1

[%poke %crud]
  bar-stack
[   i
  [ i=/behn/drip-slog
    t=[i=/clay/merge/pongo/~bacrys/pongo/only-that t=~[/gall/use/hood/0w1.KOgYF/~socryx-topled/kiln/zinc/pongo/~bacrys/pongo/0v18/main /dill //term/1]]
  ]
    t
  [ i=[i=/clay/merge/pongo/~bacrys/pongo/only-that t=[i=/gall/use/hood/0w1.KOgYF/~socryx-topled/kiln/zinc/pongo/~bacrys/pongo/0v18/main t=~[/dill //term/1]]]
    t=~[[i=//behn t=~]]
  ]
]
call: failed
/sys/vane/dill/hoon:<[296 3].[415 13]>
/sys/vane/dill/hoon:<[297 3].[415 13]>
```

After a little while, it will time out with some error and die. I can bring back the error, when it has timed out again, but anybody seen this? I tried packing and melding, but I don't know what I'm doing at all (except for a solid ~10 years of Urbit experience that tells me now is the time to just ask for some help!)

**Comment by 0x70b1a5** [comment]
Try this: 

- boot the affected ship
- once booted, the ship will immediately try to install the pongo update
- use CTRL+C to cancel this. You can press it as many times as needed, just go until you see errors indicating the install was canceled
- now, `|install ~bacrys %nectar`
- once nectar is booted, `|install ~bacrys %pongo`

**Comment by kingdonb** [comment]
Spamming Ctrl+C was the trick I needed to get me un-stuck, I'm following the rest of your suggestion now 🎉 

Thank you

```
merge into %nectar succeeded, ...
...
gall: booted %nectar
gall: booted %social-graph
...
kiln: beginning install into %pongo from ~bacrys/%pongo
> |install ~bacrys %pongo
>=
kiln: downloading update for %talk from ~sogryp-dister-dozzod-dozzod/%talk
spider got input for non-existent ~[~.khan-lard--0v1.5b1ro.cgst9.hif8o.8aiho.hf98p]
spider got input for non-existent ~[~.khan-lard--0v5.qdhco.p567b.13vtd.9ejd4.am24e]
kiln: downloading update for %groups from ~sogryp-dister-dozzod-dozzod/%groups
kiln: downloading update for %pongo from ~bacrys/%pongo
kiln: activated install into %pongo from ~bacrys/%pongo
```

I think this has helped. Other stuff that was getting blocked, is now upgrading in the background too. See you in the chat 👋

**Comment by kingdonb** [comment]
I'm back up and running. Thank you!
