### ISSUE TITLE
On Desktop - Window width resizing is broken

### ISSUE THREAD

**Issue by thelifeandtimes** [uqbar-dao/pongo#3]
If the viewport size gets too narrow, chats run off the screen:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/82244264/225408141-f81b47a4-b050-42b2-b5a4-f9aa1433b39d.png">
Seems like user sent chats are pinned to the right while received chats are pinned to the left but if the screen is two narrow (i.e. half width on an m2 macbook air) they get squeezed out instead of text wrapping.

**Comment by willbach** [comment]
Fixed in v1.0.2
