### ISSUE TITLE
Can't create a profile NFT

### ISSUE THREAD

**Issue by ngzax** [uqbar-dao/pongo#49]
this is on ~winter-paches. I have no problem with this on my other ships.

Please see the sequence of screenshots below. After that **last crazy warning about a hardware wallet** (it's not, its a plain hot wallet) then the tx disappears and nothing is set. I don't see errors in Terminal.

<img width="819" alt="pongo-prob-1-0" src="https://github.com/uqbar-dao/pongo/assets/87197/e85f2d6a-a1e9-45c3-a53c-da519e03f1a2">

----

<img width="371" alt="pongo-prob-1-1" src="https://github.com/uqbar-dao/pongo/assets/87197/5e091132-1eeb-4e79-b862-a5393ac8b87e">

----

<img width="1262" alt="pongo-prob-1-2" src="https://github.com/uqbar-dao/pongo/assets/87197/01e9586f-6d33-4009-9ed2-6d3890c41b76">

----

<img width="530" alt="pongo-prob-1-3" src="https://github.com/uqbar-dao/pongo/assets/87197/a58b29f6-3c3e-4ad8-be9a-28df4bdc7443">

----

<img width="565" alt="pongo-prob-1-4" src="https://github.com/uqbar-dao/pongo/assets/87197/5d9e6e20-31f4-45a7-a443-d9b2438a339e">

**Comment by bitful-pannul** [comment]
this was caused by trying to mint an already existing name, added a scry for checking for collision in https://github.com/uqbar-dao/pongo/pull/51
